# Generated by Django 5.2 on 2026-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='contact_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
