# Generated by Django 5.2 on 2026-09-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_message_read_at_profile_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='meet_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SkillExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_learned', models.CharField(blank=True, max_length=80)),
                ('first_taught', models.CharField(blank=True, max_length=80)),
                ('second_learned', models.CharField(blank=True, max_length=80)),
                ('second_taught', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_exchange', to='accounts.conversation')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_exchanges_started', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_exchanges_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
