# Generated by Django 5.2 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
