# Generated by Django 5.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0007_alter_emailverification_expires_at')]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
